<?php

namespace Letov\Flycatcher\Modules\Downloader\ArgsSupport;

use Letov\Flycatcher\Modules\ShellCmd\ShellCmdInterface;
use Nette\PhpGenerator\PhpNamespace;
use ReflectionClass;
use ReflectionException;

class AbstractArgsSupportCodeGenerator
{
    static function generate()
    {
        $allInterfaces = get_declared_interfaces();
        array_map(function ($interfaceFile)
        {
            require $interfaceFile;
        }, glob(__DIR__ . '/ArgInterfaces/*.php'));
        $argInterfaces = array_diff(get_declared_interfaces(), $allInterfaces);
        $argsSupportNamespace = new PhpNamespace('Letov\Flycatcher\Modules\Downloader\ArgsSupport');
        $abstractArgsSupport = $argsSupportNamespace->addClass("AbstractArgsSupport");
        foreach ($argInterfaces as $argInterface)
        {
            $abstractArgsSupport->addImplement($argInterface);
        }
        $argsStorage = $abstractArgsSupport->addProperty('argsStorage');
        $argsStorage
            ->setType('array')
            ->setProtected();
        $constructor = $abstractArgsSupport
            ->addMethod('setArgs')
            ->setProtected();
        $constructor
            ->addParameter('args')
            ->setType('array');
        $constructor
            ->addBody('$this->argsStorage = $args;');
        $getArg = $abstractArgsSupport
            ->addMethod('getArg')
            ->setProtected();
        $getArg
            ->addParameter('methodName')
            ->setType('string');
        $getArg
            ->addBody('$argName = substr($methodName, 3);')
            ->addBody('return $this->argsStorage[$argName] ?? null;');
        foreach ($argInterfaces as $argInterface)
            try {
                $interface = new ReflectionClass($argInterface);
                $interfaceMethods = $interface->getMethods();
                if (1 != count($interfaceMethods)) {
                    continue;
                }
                $interfaceMethod = $interfaceMethods[0];
                $abstractArgsSupport
                    ->addMethod($interfaceMethod->name)
                    ->setReturnType($interfaceMethod->getReturnType())
                    ->setReturnNullable()
                    ->addBody('return $this->getArg(__FUNCTION__);');
            } catch (ReflectionException $e) {
                continue;
            }
        // PhpGenerator does not support abstract classes
        $argsSupportNamespace = str_replace("class", "abstract class", $argsSupportNamespace);
        file_put_contents(__DIR__ . '/AbstractArgsSupport.php',
            "<?php\n// autogenerated file\n// DO NOT EDIT\n$argsSupportNamespace");
    }
}