<?php

declare(strict_types=1);
// autogenerated file
// DO NOT EDIT

namespace Letov\Flycatcher\Downloader\ArgsSupport;

interface ArgsSupportInterface extends ArgInterfaces\BrowserSettingsArgInterface, ArgInterfaces\CaptchaTextToImageArgInterface, ArgInterfaces\HTTPArgInterface, ArgInterfaces\PhantomJSArgInterface, ArgInterfaces\SeleniumArgInterface, ArgInterfaces\ShellArgInterface
{
    public function __construct(array $args);

    public function updateArgs(array $args);

    public function getProxy(): ?\Letov\Flycatcher\ProxyPool\ProxyInterface;

    public function getTimeout(): ?int;

    public function getCookieFilePath(): ?string;

    public function getDiskCachePath(): ?string;

    public function getLocalStoragePath(): ?string;

    public function getCaptchaApiKey(): ?string;

    public function getCaptchaSign(): ?string;

    public function getCaptchaImageSelector(): ?string;

    public function getCaptchaInputSelector(): ?string;

    public function getCaptchaFormSelector(): ?string;

    public function getCaptchaSendIncorrectSolveReport(): ?bool;

    public function getHeaders(): ?array;

    public function getHttpMethod(): ?string;

    public function getPayloadDataArray(): ?array;

    public function getPayloadDataRaw(): ?string;

    public function getPayloadDataFormArray(): ?string;

    public function getPayloadDataFormRaw(): ?string;

    public function getPhantomJSConnector(): ?string;

    public function getPhantomJSViewportWidth(): ?int;

    public function getPhantomJSViewportHeight(): ?int;

    public function getPhantomJSSnapshotSelector(): ?string;

    public function getPhantomJSSnapshotPath(): ?string;

    public function getPhantomJSSaveContentPath(): ?string;

    public function getPhantomJSSaveContentMimeFilter(): ?array;

    public function getPhantomJSSaveContentWait(): ?int;

    public function getPhantomJSClickSelectorMap(): ?array;

    public function getPhantomJSClickSelectorMapRepeat(): ?int;

    public function getOffHeadlessMode(): ?bool;

    public function getBeforeDownloadCall(): ?string;

    public function getShell(): ?\Letov\Flycatcher\Shell\ShellInterface;
}
